apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod
spec:
  serviceAccount: jenkins
  containers:
    - name: java
      image: openjdk:19-jdk
      command:
        - cat
      tty: true
    - name: docker
      image: docker:20.10
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: kubectl
      image: lachlanevenson/k8s-kubectl:v1.19.9
      command:
        - cat
      tty: true
    - name: helm
      image: lachlanevenson/k8s-helm:v3.4.2
      command:
        - cat
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json
