pipeline {
    agent any

    environment {
    		DOCKERHUB_CREDENTIALS_USR=credentials('dockerhub-cred-muhammederen')
    	}


    stages {

        stage ('Prepare') {
            steps {
               echo "started build."
            }
        }

        stage ('Maven Build') {
            steps {
                withMaven(maven: 'maven') {
                    sh 'mvn clean install '
                }
            }
        }

        stage ('Sonarqube analysis') {
            steps {
                withMaven( maven: 'maven') {
                    sh 'mvn sonar:sonar '
                }
            }
        }


        stage ('Maven Test') {
            steps {
                withMaven(maven: 'maven') {
                    sh 'mvn test '
                }
            }
        }

        stage ('Dockerhub Login') {
            steps {
                sh 'docker login -u=${DOCKER_USERNAME_MUHAMMED} -p=${DOCKER_PASSWORD_MUHAMMED}'
            }
        }


        stage ('Build Docker Image') {
            steps {
                sh 'docker build -t mhmmderen/weather-api:1.0.0 .'
            }
        }

        stage ('Image Push to Dockerhub') {
            steps {
                sh 'docker push mhmmderen/weather-api:1.0.0'
            }
        }

        stage ('Image pull from Dockerhub') {
            steps {
                sh 'docker-compose pull'
            }
        }

        stage ('Deploy Project with docker-compose-prod file') {
            steps {
                sh 'docker-compose up -d'
            }
        }

    }
}
